### ISSUE TITLE
tophat license

### ISSUE THREAD

**Issue by wookietreiber** [infphilo/tophat#11]
There is both a LICENSE file and a COPYING file, which contain the boost license and the perl artistic license, respectively. Is tophat dual-licensed or is this a mistake?

**Comment by wookietreiber** [comment]
Ping. Anyone?

**Comment by infphilo** [comment]
I just deleted a COPYING file - like Cufflinks, TopHat uses Boost Software License, Version 1.0.

**Comment by wookietreiber** [comment]
Thank you for the clarification.
