### ISSUE TITLE
updated tarball (intervaltree, sortedcontainers), wrong install directory

### ISSUE THREAD

**Issue by wookietreiber** [infphilo/tophat#22]
We at Arch Linux just realized that the tarball of 2.1.0 (http://ccb.jhu.edu/software/tophat/downloads/tophat-2.1.0.tar.gz) got updated. We noticed, because the md5 of the tarball changed. Unfortunately, there was neither an update notice about this (which would have been ok) nor a version increment to 2.1.1 (which would have been better practice). Please do understand that these silent updates are bad open source software release practice. I (and I expect most people of the community would agree with me) would like to have a more open release practice in the future.

Apparently, from looking at the `diff` of the old and new tarballs, the Python packages `intervaltree` and `sortedcontainers` where originally missing and got added by this change.

The current version of the tarball installs these Python packages to `$(DESTDIR)$(bindir)` which is not the correct install location for Python packages on Linux / Unix distributions. Instead they should be installed to the `site-packages` directory of the used Python version that is detected via the `PYTHON` environment variable that is picked up during `configure` (most OS's of today ship with both Python 2 and Python 3).

**Comment by gpertea** [comment]
While in principle I agree with these points, we'd like to consider an exception for the last one - the  distribution of intervaltree and sortedcontainers code, as some users might not be able to handle installation of Python modules in a common`site-packages` area - we wanted to provide a somewhat standalone, encapsulated install for regular users, yet with the ability to easily convert it to a common installation if needed..
